# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "say_goodbye": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://JugglingNumbers.github.io/test_nbdev_template/"

git_url = "https://github.com/JugglingNumbers/test_nbdev_template/tree/main/"

def custom_doc_links(name): return None
